version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: biblioteca
    ports:
      - 5432:5432

  app:
    build: .
    command: yarn dev
    environment:
      - MAILHOG_HOST=mailhog
    ports:
      - 3333:3333

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
