version: "3"

services:
  app:
    build: .
    command: yarn dev
    environment:
      - MAILHOG_HOST=mailhog
    ports:
      - 3333:3333

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
